import { Post } from '@/types/post';
import { Store } from '@/types/store';
import { Notification } from '@/types/notification';

// Mock Store Data
export const mockStores: Store[] = [
  {
    id: 'store1',
    name: 'マルエツ 東京駅店',
    address: '東京都千代田区丸の内1-1-1',
    latitude: 35.681236,
    longitude: 139.767125,
    openStatus: 'open',
    openingHours: '9:00 - 22:00',
    phone: '03-1234-5678',
    distance: 0.8,
    hasDiscount: true,
    posts: 3,
  },
  {
    id: 'store2',
    name: 'イトーヨーカドー 秋葉原店',
    address: '東京都千代田区外神田1-2-3',
    latitude: 35.698353,
    longitude: 139.773115,
    openStatus: 'open',
    openingHours: '10:00 - 21:00',
    phone: '03-2345-6789',
    distance: 1.2,
    hasDiscount: true,
    posts: 2,
  },
  {
    id: 'store3',
    name: 'ライフ 新宿店',
    address: '東京都新宿区新宿3-4-5',
    latitude: 35.690921,
    longitude: 139.700258,
    openStatus: 'open',
    openingHours: '24時間営業',
    phone: '03-3456-7890',
    distance: 1.5,
    hasDiscount: false,
    posts: 0,
  },
  {
    id: 'store4',
    name: 'まいばすけっと 渋谷店',
    address: '東京都渋谷区渋谷1-2-3',
    latitude: 35.658517,
    longitude: 139.701334,
    openStatus: 'closed',
    openingHours: '7:00 - 23:00',
    phone: '03-4567-8901',
    distance: 2.1,
    hasDiscount: false,
    posts: 0,
  },
  {
    id: 'store5',
    name: 'オーケー 池袋店',
    address: '東京都豊島区池袋2-3-4',
    latitude: 35.729503,
    longitude: 139.711684,
    openStatus: 'open',
    openingHours: '9:00 - 22:00',
    phone: '03-5678-9012',
    distance: 2.5,
    hasDiscount: true,
    posts: 1,
  },
];

// Mock Post Data
export const mockPosts: Post[] = [
  {
    id: 'post1',
    author: {
      id: 'user1',
      name: 'タロウ',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    storeName: 'マルエツ 東京駅店',
    content: '惣菜コーナーのお弁当が全品30%オフになっています！まだたくさん残ってます。',
    image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: '弁当',
    discountRate: 30,
    remainingItems: 10,
    expiryTime: '20:00',
    createdAt: '2025-04-10T15:30:00.000Z',
    likes: 12,
    comments: 3,
  },
  {
    id: 'post2',
    author: {
      id: 'user2',
      name: 'ハナコ',
      avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    storeName: 'イトーヨーカドー 秋葉原店',
    content: '精肉コーナーの豚肉が全品50%オフ！今日の夕方までだそうです。',
    image: 'https://images.pexels.com/photos/128401/pexels-photo-128401.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: '肉',
    discountRate: 50,
    remainingItems: 5,
    expiryTime: '18:00',
    createdAt: '2025-04-10T14:45:00.000Z',
    likes: 8,
    comments: 1,
  },
  {
    id: 'post3',
    author: {
      id: 'user3',
      name: 'ケンジ',
      avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    storeName: 'オーケー 池袋店',
    content: '野菜コーナーでトマトが特売中！かなり新鮮です。',
    image: 'https://images.pexels.com/photos/96616/pexels-photo-96616.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: '野菜',
    discountRate: 20,
    remainingItems: 15,
    expiryTime: null,
    createdAt: '2025-04-10T12:15:00.000Z',
    likes: 5,
    comments: 0,
  },
  {
    id: 'post4',
    author: {
      id: 'user4',
      name: 'ミカ',
      avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    },
    storeName: 'マルエツ 東京駅店',
    content: '閉店間際にパンコーナーのパンが全品70%オフになりました！',
    image: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'その他',
    discountRate: 70,
    remainingItems: 8,
    expiryTime: '22:00',
    createdAt: '2025-04-10T11:30:00.000Z',
    likes: 15,
    comments: 4,
  },
  {
    id: 'post5',
    author: {
      id: 'user1',
      name: 'タロウ',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    storeName: 'イトーヨーカドー 秋葉原店',
    content: '鮮魚コーナーの刺身が全品40%オフです。夕食にいかがですか？',
    image: 'https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: '魚',
    discountRate: 40,
    remainingItems: 3,
    expiryTime: '19:00',
    createdAt: '2025-04-10T10:45:00.000Z',
    likes: 7,
    comments: 2,
  },
];

// Mock Notification Data
export const mockNotifications: Notification[] = [
  {
    id: 'notif1',
    type: 'discount',
    message: 'マルエツ 東京駅店で新しい値引き情報が投稿されました：惣菜コーナーのお弁当が全品30%オフ',
    read: false,
    timeAgo: '10分前',
  },
  {
    id: 'notif2',
    type: 'store',
    message: 'お気に入りのイトーヨーカドー 秋葉原店で3件の値引き情報があります',
    read: false,
    timeAgo: '1時間前',
  },
  {
    id: 'notif3',
    type: 'user',
    message: 'ハナコさんがあなたの投稿にいいねしました',
    read: true,
    timeAgo: '3時間前',
  },
  {
    id: 'notif4',
    type: 'discount',
    message: 'オーケー 池袋店で野菜の値引き情報が投稿されました：トマトが20%オフ',
    read: true,
    timeAgo: '昨日',
  },
  {
    id: 'notif5',
    type: 'user',
    message: 'ケンジさんがあなたの投稿にコメントしました',
    read: true,
    timeAgo: '2日前',
  },
  {
    id: 'notif6',
    type: 'store',
    message: '近くに新しいスーパー「マックスバリュ 新橋店」がオープンしました',
    read: true,
    timeAgo: '3日前',
  },
];